import turtle

scn = turtle.Screen()
bob = turtle.Turtle()
joe = turtle.Turtle()
jim = turtle.Turtle()
sue = turtle.Turtle()

bob.speed(10)
sue.speed(10)
joe.speed(10)
jim.speed(10)

sue.penup()
sue.goto(-357, -200)
sue.color("forest green")
sue.pendown()
sue.begin_fill()
sue.forward(710)
sue.right(90)
sue.forward(135)
sue.right(90)
sue.forward(710)
sue.right(90)
sue.forward(135)
sue.end_fill()

bob.penup()
bob.goto(-357,-200)
bob.color("red")
bob.pendown()
bob.begin_fill()
bob.left(90)
bob.forward(200)
bob.right(90)
bob.forward(200)
bob.right(90)
bob.forward(200)
bob.right(90)
bob.forward(200)
bob.end_fill()

jim.penup()
jim.goto(-357, 0)
jim.pendown()
jim.begin_fill()
jim.left(45)
jim.forward(145)
jim.right(90)
jim.forward(143)
jim.end_fill()
jim.penup()
jim.goto(-270,-200)
jim.color("saddle brown")
jim.left(135)
jim.pendown()
jim.forward(75)


turtle.exitonclick()